feat(proof): Include leaf that advances the namespace in absence proofs
Sovereign-Labs/nmt-rs pull request #12
Opened 2023-07-05 17:07 UTC by zvolin

references #10

Based on the Celestia nmt specification:
https://github.com/celestiaorg/nmt/blob/master/docs/spec/nmt.md\#verification-of-nmt-absence-proof

Above docs state that when creating an absence proof, the chosen leaf should be of higher namespace than the namespace that is being proven. This will allow for compatibility with the proofs created by the go implementation.

As the range proof for the range [leaf_idx, leaf_idx + 1) must still include the left sibling of the leaf, and that sibling will inherit the max namespace from the leaf at leaf_idx - 1, it is still self containing and doesn't need additional data to prove the absence.

2023-07-06 09:03 UTC, bkolad commented
thx @zvolin, the PR lgtm but I would prefer if @preston-evans98 review it as well (he will be back from holiday on Mon).

2023-07-09 15:15 UTC, preston-evans98 requested changes

2023-07-09 15:15 UTC, preston-evans98 commented on src/lib.rs
> +                if namespace >= leaf.min_namespace() {
@zvolin, this looks like it might introduce a bug. Previously (since we used a different proof format), we checked that the absent namespace was *less than the namespace of its left sibling* (here on line 332/292) and then checked that the absent namespace was *greater than the namespace of its right sibling* (on line 338/298). 

Since we've inverted the first check, we need to invert the second one as well. Otherwise, we'll be making two separate checks that the the provided namespace actually precedes its purported right sibling, but none that it follows its purported left sibling/

2023-07-09 19:38 UTC, zvolin commented on src/lib.rs
> +                if namespace >= leaf.min_namespace() {
good catch, done

2023-07-09 20:49 UTC, preston-evans98 approved these changes

2023-07-09 20:52 UTC, preston-evans98 commented
@zvolin the new version looks correct, but it's a little worrying that our test suite didn't catch it. Is this PR blocking work on anything else? If not, let's try to introduce a regression test (or, even better, a `proptest`) which would catch this bug.

2023-07-09 22:03 UTC, zvolin commented
I also thought about this test and it seems to be impossible to create using public api. I'll add some test only way tho

2023-07-10 12:33 UTC, zvolin commented
@preston-evans98 I've added some test that triggers this branch. Before the fix [from your comment](https://github.com/Sovereign-Labs/nmt-rs/pull/12#discussion_r1257499895), the test would fail with `panic!` from `hash_nodes`.
I'm not sure if I like that test tho, and I'm not sure how to write it better or using proptest, so up to you what to do with that.

2023-07-12 18:56 UTC, zvolin commented
Hi @preston-evans98. I know the test isn't beautiful. Do you have any comments what you'd expect to change in it or any directions how would you see those proptests so we could proceed with it?

I'm not rebasing #13 and #14 yet to not do double work

2023-07-12 18:57 UTC, zvolin commented
btw the coverage failure seems like something random

2023-07-12 19:15 UTC, preston-evans98 approved these changes

2023-07-12 19:17 UTC, preston-evans98 commented
Hi @zvolin, sorry I missed the first update here. The test looks good enough, thanks! 

Btw, I see that you've been updating PRs by amending the commit and force pushing. If it's possible to do just add another commit in future, we definitely prefer that! We squash on merge anyway, so it won't pollute the history - but it's easier to review if you can compare across revisions.

2023-07-12 19:47 UTC, zvolin commented
> We squash on merge anyway, so it won't pollute the history

Hmmm, for some reason I thought you do the ff-only merges. Sure, will keep in mind. That definitely have worked better in gitlab :sweat_smile:

Can you retrigger the cov then and merge? I'll prepare the rest of PR's then

2023-07-12 20:10 UTC, merged